name: optimizer_exp
dependencies:
  - pip
  - python>=3.7
  - pip:
    - numpy 
    - pandas
    - matplotlib
    - seaborn 
    - scipy==1.8.0
    - smt==1.2.0
    - tqdm
    - cocopp==2.6
    - pyswarms
    - pygad
    - scikit-learn
    - pyDOE2